apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_DB: "docvault"
  POSTGRES_USER: "docvault_user"
  POSTGRES_PASSWORD: "changeme"
  jwt-secret: "faizan-hamza-secret-2024"
